title: Tyler Chandross-Cohen
description: Food Microbiology | <em>Bacillus cereus</em> | Genomics & Cytotoxicity
theme: minima

header_pages:
  - index.md
  - publications.md
  - posters.md
  - cv.md
  - media.md
  - conference-blogs.md
