title: Tyler Chandross-Cohen
description: Food Microbiology | Bacillus cereus | Whole Genome Sequencing
theme: minima

header_pages:
  - index.md
  - publications.md
  - posters.md
  - cv.md
  - media.md
  - conference-blogs.md

