title: Tyler Chandross-Cohen
description: Food Microbiology | Bacillus cereus | Whole Genome Sequencing
theme: minima

google_analytics: G-2L0B6GNZT7

header_pages:
  - index.md
  - publications.md
  - posters.md
  - cv.md
  - media.md
  - conference-blogs.md

